### ISSUE TITLE
Rethink `Motor` constructor arguments.

### ISSUE THREAD

**Issue by Tropix126** [pros-rs/pros-rs#49]
## What's the motivation for this feature?
This is pretty important. The state setters that are most likely going to vary for users at construction time are as follows (most likely to least likely):
- Port number (obviously)
- Gearset
- Reverse flag
- Brake mode
- Encoder units

This is (for the most part) reflected in PROS' C++ API for motor constructors:
![image](https://github.com/pros-rs/pros-rs/assets/42101043/03147192-b701-4449-bb0e-34fc6d4a6a38)

Currently we only allow passing in brake mode to the constructor, which isn't really useful to the majority of people constructing motors. Most competition uses facilitate motors being on coast anyways, and the setter's there for people wanting to modify that flag:

```rs
pub fn new(port: SmartPort, brake_mode: BrakeMode) -> ...;
```

## Describe the solution you'd like
Replace the `brake_mode` argument with `gearset` and `reverse` arguments to `Motor::new`:
```rs
pub fn new(port: SmartPort, gearset: Gearset, reverse: bool) -> ...;
```

Incidentally, this now matches VEXCode's motor constructor signature 😅:
![image](https://github.com/pros-rs/pros-rs/assets/42101043/189ca6c8-8067-4be2-868d-d3109791dc04)

## Describe the drawbacks, if any
This will create a breaking change (semver:major).

## Describe the alternative solutions, if any
- Keep the function signature as-is. I really don't advise this.
- Add all the above arguments, but additionally allow setting `brake_mode` at construct-time. This also is pretty reasonable, but would require people to explicitly specify a brake mode every time they want to make a motor, which isn't all that common.

## Additional context
Nope.

**Comment by Gavin-Niederman** [comment]
Encoder units don't need to be a parameter because of the `Position` type we have.
